project_name: k8s-s2s-auth
builds:
- goos:
  - linux
  - darwin
  - windows
archives:
- name_template: "{{ .ProjectName }}_{{ .Os }}_{{ .Arch }}"
  format: binary
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
