name: main

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Build
        run: go build ./...

  release:
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'push' && startsWith(github.ref, 'refs/tags/v')
    steps:
      - uses: actions/setup-go@v1
        with:
          go-version: '1.15'

      - uses: actions/checkout@v2

      - name: Install Tools
        env:
          GO111MODULE: on 
        run: |
          cd /tmp
          go get github.com/google/ko/cmd/ko@v0.6.0
          echo "$( go env GOPATH )/bin" >> $GITHUB_PATH

      - name: Docker Hub Release
        env:
          KO_DOCKER_REPO: dsbrng25b
        run: |
            echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u dsbrng25b --password-stdin
            ko publish -t "${GITHUB_REF##*/}" -t latest -B .

      - name: Github Release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          sudo snap install goreleaser --classic
          goreleaser release
